# Generated by Django 3.1.6 on 2021-02-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(default='', max_length=8, unique=True)),
                ('roomHost', models.CharField(max_length=50, unique=True)),
                ('pausePermision', models.BooleanField(default=False)),
                ('skipVotes', models.IntegerField(default=1)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
