# Generated by Django 3.1.6 on 2021-02-15 20:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomId',
            field=models.CharField(default=api.models.generateUniqueCode, max_length=8, unique=True),
        ),
    ]
